- id: '1636050957204'
  alias: TV cabinet lights
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.lg_tv_remote
    to: playing
  - platform: sun
    event: sunset
  condition:
  - condition: and
    conditions:
    - condition: sun
      after: sunset
    - condition: state
      entity_id: media_player.lg_tv_remote
      state: playing
  action:
  - type: turn_on
    device_id: 7bd1968937b3e53a8fe785b06b9d5d50
    entity_id: light.tv_cabinet_left
    domain: light
  - type: turn_on
    device_id: d41155d49a64ae65b1fcaf9db11c0131
    entity_id: light.tv_cabinet_right
    domain: light
  mode: single
- id: '1636292973585'
  alias: Garden lights
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: time
    before: '23:00:00'
  action:
  - service: switch.turn_on
    target:
      entity_id:
      - switch.backyard_lights
  mode: single
- id: '1636445923540'
  alias: Away from home
  description: ''
  trigger:
  - platform: state
    entity_id: group.persons
    to: not_home
  condition: []
  action:
  - service: light.turn_off
    target:
      area_id:
      - c9c7d949cb959b8436f04d3b8e02018a
      - 5725600297af4a14beb939fde831b3e9
      - e0451735c3764eebbf1c3fece20c87e9
      - 940887afcb1047b2b74fad4a446ce8b9
      - 4ba690e438d54e1ca7f466c0de5d960b
      - hallway
      entity_id:
      - input_boolean.office
    data: {}
  - service: media_player.turn_off
    data: {}
    target:
      entity_id: media_player.lg_tv_remote
  - service: climate.set_preset_mode
    data:
      preset_mode: Manual
    target:
      device_id: 78450d0b88d1fdf35297da6ed09f4f8b
  - service: climate.set_temperature
    data:
      temperature: 15
    target:
      entity_id: climate.nefit
  - service: climate.turn_off
    data: {}
    target:
      entity_id: climate.office
  mode: single
- id: '1639577789678'
  alias: 'Turn off lights when it''s getting light '
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.solar_radiation
    above: '13'
  condition: []
  action:
  - service: homeassistant.turn_off
    target:
      area_id:
      - 5725600297af4a14beb939fde831b3e9
      - c9c7d949cb959b8436f04d3b8e02018a
      - 940887afcb1047b2b74fad4a446ce8b9
  mode: single
- id: '1648526720153'
  alias: Turn off bedside light André
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.sm_g991b_is_charging
    to: 'off'
    from: 'on'
  condition:
  - condition: time
    after: 05:00:00
    before: '10:00:00'
  action:
  - type: turn_off
    device_id: dfedf6a047a478d4540755ce837b2d82
    entity_id: light.ikea_nightlight_01
    domain: light
  mode: single
- id: '1665522807559'
  alias: Livingroom lights off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.shelly1_livingroom
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: media_player.lg_tv_remote
    state: 'off'
  action:
  - type: turn_off
    device_id: d41155d49a64ae65b1fcaf9db11c0131
    entity_id: light.tv_cabinet_right
    domain: light
  - type: turn_off
    device_id: 7bd1968937b3e53a8fe785b06b9d5d50
    entity_id: light.tv_cabinet_left
    domain: light
  mode: single
- id: '1666373128921'
  alias: Slaaptrainer Weekend
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - type: turn_off
    device_id: 55ab137d1334f604e4eaf1080252f16d
    entity_id: switch.blitzwolf_bwshp15_01
    domain: switch
  mode: single
- id: '1666462891423'
  alias: Slaaptrainer Mo, Tu, Th, Fr
  description: ''
  trigger:
  - platform: time
    at: 06:00:00
  condition:
  - condition: time
    weekday:
    - fri
    - thu
    - tue
    - mon
  action:
  - type: turn_off
    device_id: 55ab137d1334f604e4eaf1080252f16d
    entity_id: switch.blitzwolf_bwshp15_01
    domain: switch
  mode: single
- id: '1668957815753'
  alias: Turn off bedside light Lize
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.sgs10_lize_is_aan_het_opladen
    to: 'off'
    from: 'on'
  condition:
  - condition: time
    after: 05:00:00
    before: '10:00:00'
  action:
  - type: turn_off
    device_id: faad4b192378e316257a2e8d2980cdcd
    entity_id: light.ikea_nightlight_02
    domain: light
  mode: single
- id: '1668971498514'
  alias: Wake up light André
  description: ''
  trigger:
  - platform: time
    at: input_datetime.next_alarm
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: person.andre_de_zwart
      state: home
    - condition: state
      entity_id: binary_sensor.sm_g991b_is_charging
      state: 'on'
    - condition: state
      entity_id: light.ikea_nightlight_01
      state: 'off'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 1
      color_temp: 500
    target:
      device_id: dfedf6a047a478d4540755ce837b2d82
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1800
      brightness_pct: 100
    target:
      device_id: dfedf6a047a478d4540755ce837b2d82
  mode: single
- id: '1669754804462'
  alias: Android alarm time
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.phone_andre_next_alarm
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.phone_andre_next_alarm
      state:
      - unavailable
      - unknown
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: input_datetime.set_datetime
    data_template:
      datetime: '{{ as_timestamp(states(''sensor.phone_andre_next_alarm'')) | timestamp_custom(''%Y-%m-%d
        %H:%M:00'') }}'
    target:
      entity_id: input_datetime.next_alarm
  mode: single
- id: '1673262664635'
  alias: Turn off hallway light after 7 min
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.shelly1_hallway
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.xiaomi_door_01_contact
    to: 'on'
  condition:
  - condition: state
    entity_id: light.shelly1_hallway
    state: 'on'
  action:
  - delay:
      hours: 0
      minutes: 7
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.shelly1_hallway
  mode: restart
- id: '1676100536712'
  alias: Slaaptrainer aan 19:00
  description: ''
  trigger:
  - platform: time
    at: '19:00:00'
  condition: []
  action:
  - type: turn_on
    device_id: 55ab137d1334f604e4eaf1080252f16d
    entity_id: switch.blitzwolf_bwshp15_01
    domain: switch
  mode: single
- id: '1678219014663'
  alias: Arrive back home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.andre_de_zwart
    to: home
  - platform: state
    entity_id:
    - person.lize_wasmus
    to: home
  condition: []
  action:
  - service: climate.set_preset_mode
    data:
      preset_mode: Clock
    target:
      device_id: 78450d0b88d1fdf35297da6ed09f4f8b
  - if:
    - condition: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: -3
    then:
    - service: light.turn_on
      data: {}
      target:
        entity_id:
        - light.outdoor_light
        - light.shelly1_hallway
  - if:
    - condition: and
      conditions:
      - condition: zone
        entity_id: person.andre_de_zwart
        zone: zone.home
      - condition: state
        entity_id: input_select.washing_machine
        state: Finished
    then:
    - service: notify.mobile_app_phone_andre
      data:
        message: De was is klaar!
        data:
          tag: washing_machine
    alias: If André comes home & the washing machine is finished, then send a notification
  - if:
    - condition: and
      conditions:
      - condition: zone
        entity_id: person.lize_wasmus
        zone: zone.home
      - condition: state
        entity_id: input_select.washing_machine
        state: Finished
    then:
    - service: notify.mobile_app_sgs10_lize
      data:
        data:
          tag: washing_machine
        message: De was is klaar!
    alias: If Lize comes home & the washing machine is finished, then send a notification
  mode: single
- id: '1682845588155'
  alias: Washing machine - Washing
  description: Set washing machine to "washing" state
  trigger:
  - platform: numeric_state
    entity_id: sensor.washing_machine_power
    for:
      hours: 0
      minutes: 3
      seconds: 0
    attribute: power
    above: 5
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_select.washing_machine
        state: 'Off'
      sequence:
      - service: input_select.select_option
        data:
          option: Washing
        target:
          entity_id: input_select.washing_machine
    alias: State to Washing
  mode: single
- id: '1682846009852'
  alias: Washing machine - Finished
  description: Send notification when the washing machine is done.
  trigger:
  - platform: numeric_state
    entity_id: sensor.washing_machine_power
    for:
      hours: 0
      minutes: 2
      seconds: 0
    attribute: power
    below: 1
  condition:
  - condition: state
    entity_id: input_select.washing_machine
    state: Washing
  action:
  - service: input_select.select_option
    data:
      option: Finished
    target:
      entity_id: input_select.washing_machine
  - choose:
    - conditions:
      - condition: state
        entity_id: person.andre_de_zwart
        state: home
      sequence:
      - service: notify.mobile_app_phone_andre
        data:
          message: De was is klaar!
          data:
            persistent: true
            tag: washing_machine
    alias: Notify André if home
  - choose:
    - conditions:
      - condition: state
        entity_id: person.lize_wasmus
        state: home
      sequence:
      - service: notify.mobile_app_sgs10_lize
        data:
          message: De was is klaar!
    alias: Notify Lize if home
  mode: single
- id: '1683692334259'
  alias: Slaaptrainer Wednesday
  description: ''
  trigger:
  - platform: time
    at: 06:30:00
  condition:
  - condition: time
    weekday:
    - wed
  action:
  - type: turn_off
    device_id: 55ab137d1334f604e4eaf1080252f16d
    entity_id: switch.blitzwolf_bwshp15_01
    domain: switch
  mode: single
- id: '1684870809099'
  alias: Sync IP cam time
  description: ''
  trigger:
  - platform: time_pattern
    hours: /1
  - platform: homeassistant
    event: shutdown
  condition: []
  action:
  - service: button.press
    data: {}
    target:
      entity_id: button.frontdoor_set_system_date_and_time
  mode: single
- id: '1684871522129'
  alias: Test persistent message
  description: ''
  trigger: []
  condition: []
  action:
  - service: notify.mobile_app_phone_andre
    data:
      message: Persistent test bericht
      data:
        persistent: true
        tag: washing_machine
  mode: single
- id: '1684871753906'
  alias: test persistent dismiss
  description: ''
  trigger: []
  condition: []
  action:
  - service: notify.mobile_app_phone_andre
    data:
      message: clear_notification
      data:
        tag: washing_machine
  mode: single
- id: '1684872146878'
  alias: Washing Machine - Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.xiaomi_door_03_contact
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: input_select.washing_machine
      state: Finished
    - condition: state
      entity_id: input_select.washing_machine
      state: Washing
  action:
  - service: input_select.select_option
    data:
      option: 'Off'
    target:
      entity_id: input_select.washing_machine
  - service: notify.mobile_app_phone_andre
    data:
      message: clear_notification
      data:
        tag: washing_machine
  - service: notify.mobile_app_sgs10_lize
    data:
      message: clear_notification
      data:
        tag: washing_machine
  mode: single
- id: '1689508842876'
  alias: Tablet battery low
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.sgts5e_batterijniveau
    below: '30'
  - platform: numeric_state
    entity_id: sensor.sgts5e_batterijniveau
    below: '20'
  - platform: numeric_state
    entity_id: sensor.sgts5e_batterijniveau
    below: '15'
  - platform: numeric_state
    entity_id: sensor.sgts5e_batterijniveau
    below: '10'
  - platform: numeric_state
    entity_id: sensor.sgts5e_batterijniveau
    below: '5'
  condition:
  - condition: state
    entity_id: sensor.sgts5e_batterij_laadstatus
    state: discharging
  action:
  - service: notify.mobile_app_phone_andre
    data:
      message: Tablet batterij niveau op {{states.sensor.sgts5e_batterijniveau.state_with_unit}}!
        Tijd om op te laden.
      data:
        tag: tablet_battery_low
  - service: notify.mobile_app_sgs10_lize
    data:
      message: Tablet batterij niveau op {{states.sensor.sgts5e_batterijniveau.state_with_unit}}!
        Tijd om op te laden.
      data:
        tag: tablet_battery_low
  mode: single
- id: '1689509348992'
  alias: Tablet is charging
  description: Clear notification when tablet is charging
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.sgts5e_is_aan_het_opladen
    from: 'off'
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.sgts5e_batterijniveau
    below: 30
  action:
  - service: notify.mobile_app_phone_andre
    data:
      message: clear_notification
      data:
        tag: tablet_battery_low
  - service: notify.mobile_app_sgs10_lize
    data:
      message: clear_notification
      data:
        tag: tablet_battery_low
  mode: single
