- id: '1619375794749'
  alias: Left at KDV notification
  description: ''
  trigger:
  - platform: zone
    entity_id:
    - person.andre_de_zwart
    - person.lize_wasmus
    zone: zone.kdv_het_tuinhuis
    event: leave
  condition:
  - condition: time
    after: '16:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: "{% if 'André' in trigger.to_state.attributes.friendly_name %}\n  notify.mobile_app_sgs10_lize\n\
      {% else %}\n  notify.mobile_app_sgs10_andre\n{% endif %}\n"
    data:
      message: '{{ trigger.to_state.attributes.friendly_name }} is vertrokken bij Het Tuinhuis'
  mode: single