- id: 'front_door_light_evening'
  alias: Turn on the front door in the evening
  description: ''
  trigger:
  - below: '-4.0'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state_attr(''sun.sun'', ''elevation'') }}'
  condition:
  - after: '15:00:00'
    before: '22:45:00'
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - device_id: 5aca4596f22b4a6da91634d6c84681e9
    domain: switch
    entity_id: switch.outside
    type: turn_on
- id: 'front_door_light_morning'
  alias: Turn on the front door light in the morning
  description: ''
  trigger:
  - below: '-4.0'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state_attr(''sun.sun'', ''elevation'') }}'
  condition:
  - after: '6:00:00'
    before: '7:15:00'
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - device_id: 5aca4596f22b4a6da91634d6c84681e9
    domain: switch
    entity_id: switch.outside
    type: turn_on
- id: 'front_door_light_nighttime_daytime'
  alias: Turn off front door light during the night or during the day
  description: ''
  trigger:
  - at: '23:00:00'
    platform: time
  - at: '7:30:00'
    platform: time
  condition: []
  action:
  - device_id: 5aca4596f22b4a6da91634d6c84681e9
    domain: switch
    entity_id: switch.outside
    type: turn_off
- id: 'trash_collection_notification_day_before_0'
  alias: 'Trash collection notification day before 0'
  trigger:
  - platform: time
    at: '19:30'
  condition:
  - condition: and
    conditions:
    - condition: template
      value_template: >
        {% if (as_timestamp(now()) > (as_timestamp(states.sensor.afvalkalender_event_0.attributes.start) - 43200)) %}
          true
        {% endif %}
    - condition: template
      value_template: >
        {% if (as_timestamp(now()) < (as_timestamp(states.sensor.afvalkalender_event_0.attributes.start))) %}
          true
        {% endif %}
  action:
  - service: notify.telegram_andre
    data_template:
      message: '{{states.sensor.afvalkalender_event_0.attributes.name}} wordt morgen opgehaald.'
  - service: notify.telegram_lize
    data_template:
      message: '{{states.sensor.afvalkalender_event_0.attributes.name}} wordt morgen opgehaald.'
- id: 'trash_collection_notification_day_before_1'
  alias: 'Trash collection notification day before 1' 
  trigger:
  - platform: time
    at: '19:30'
  condition:
  - condition: and
    conditions:
    - condition: template
      value_template: >
        {% if (as_timestamp(now()) > (as_timestamp(states.sensor.afvalkalender_event_1.attributes.start) - 43200)) %}
          true
        {% endif %}
    - condition: template
      value_template: >
        {% if (as_timestamp(now()) < (as_timestamp(states.sensor.afvalkalender_event_1.attributes.start))) %}
          true
        {% endif %}
  action:
  - service: notify.telegram_andre
    data_template:
      message: '{{states.sensor.afvalkalender_event_1.attributes.name}} wordt morgen opgehaald.'
  - service: notify.telegram_lize
    data_template:
      message: '{{states.sensor.afvalkalender_event_1.attributes.name}} wordt morgen opgehaald.' 
- id: 'trash_collection_notification_same_day_0'
  alias: 'Trash collection notification reminder same day 0'
  trigger:
  - platform: time
    at: '06:15'
  condition:
  - condition: template
    value_template: >
      {% if (as_timestamp(now()) > (as_timestamp(states.sensor.afvalkalender_event_0.attributes.start))) %}
        true
      {% endif %}
  action:
  - service: notify.telegram_andre
    data_template:
      message: '{{states.sensor.afvalkalender_event_0.attributes.name}} wordt vandaag opgehaald!'
  - service: notify.telegram_lize
    data_template:
      message: '{{states.sensor.afvalkalender_event_0.attributes.name}} wordt vandaag opgehaald!'
   
