- id: '1619375794749'
  alias: Left at KDV notification
  description: ''
  trigger:
  - platform: zone
    entity_id:
    - person.andre_de_zwart
    - person.lize_wasmus
    zone: zone.kdv_het_tuinhuis
    event: leave
  condition:
  - condition: time
    after: '16:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: "{% if 'André' in trigger.to_state.attributes.friendly_name %}\n  notify.mobile_app_sgs10_lize\n{%
      else %}\n  notify.mobile_app_phone_andre\n{% endif %}\n"
    data:
      message: '{{ trigger.to_state.attributes.friendly_name }} is vertrokken bij
        Het Tuinhuis'
  mode: single
- id: '1636050957204'
  alias: TV cabinet lights
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.lg_tv_remote
    to: playing
  - platform: sun
    event: sunset
  condition:
  - condition: and
    conditions:
    - condition: sun
      after: sunset
    - condition: state
      entity_id: media_player.lg_tv_remote
      state: playing
  action:
  - type: turn_on
    device_id: 7bd1968937b3e53a8fe785b06b9d5d50
    entity_id: light.tv_cabinet_left
    domain: light
  - type: turn_on
    device_id: d41155d49a64ae65b1fcaf9db11c0131
    entity_id: light.tv_cabinet_right
    domain: light
  mode: single
- id: '1636292973585'
  alias: Garden lights
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: time
    before: '23:00:00'
  action:
  - service: switch.turn_on
    target:
      entity_id:
      - switch.backyard_lights
  mode: single
- id: '1636445923540'
  alias: Away from home
  description: ''
  trigger:
  - platform: state
    entity_id: group.persons
    to: not_home
  condition: []
  action:
  - service: light.turn_off
    target:
      area_id:
      - c9c7d949cb959b8436f04d3b8e02018a
      - 5725600297af4a14beb939fde831b3e9
      - e0451735c3764eebbf1c3fece20c87e9
      - 940887afcb1047b2b74fad4a446ce8b9
      - 4ba690e438d54e1ca7f466c0de5d960b
      - hallway
      entity_id:
      - input_boolean.office
    data: {}
  - service: climate.turn_off
    data: {}
    target:
      entity_id: climate.office
  - service: media_player.turn_off
    data: {}
    target:
      entity_id: media_player.lg_tv_remote
  mode: single
- id: '1639577789678'
  alias: 'Turn off lights when it''s getting light '
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.solar_radiation
    above: '13'
  condition: []
  action:
  - service: homeassistant.turn_off
    target:
      area_id:
      - 5725600297af4a14beb939fde831b3e9
      - c9c7d949cb959b8436f04d3b8e02018a
      - 940887afcb1047b2b74fad4a446ce8b9
  mode: single
- id: '1648526720153'
  alias: Turn off bedside light André
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.sm_g991b_is_charging
    to: 'off'
    from: 'on'
  condition: []
  action:
  - type: turn_off
    device_id: dfedf6a047a478d4540755ce837b2d82
    entity_id: light.ikea_nightlight_01
    domain: light
  mode: single
- id: '1665522807559'
  alias: Livingroom lights off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.shelly1_livingroom
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: media_player.lg_tv_remote
    state: 'off'
  action:
  - type: turn_off
    device_id: d41155d49a64ae65b1fcaf9db11c0131
    entity_id: light.tv_cabinet_right
    domain: light
  - type: turn_off
    device_id: 7bd1968937b3e53a8fe785b06b9d5d50
    entity_id: light.tv_cabinet_left
    domain: light
  mode: single
- id: '1666373128921'
  alias: Slaaptrainer Weekend 6:30
  description: ''
  trigger:
  - platform: time
    at: 06:30:00
  condition:
  - condition: time
    weekday:
    - sat
    - sun
    - wed
  action:
  - type: turn_off
    device_id: 55ab137d1334f604e4eaf1080252f16d
    entity_id: switch.blitzwolf_bwshp15_01
    domain: switch
  mode: single
- id: '1666462891423'
  alias: Slaaptrainer Weekdays 6:15
  description: ''
  trigger:
  - platform: time
    at: 06:15:00
  condition:
  - condition: time
    weekday:
    - fri
    - thu
    - tue
    - mon
  action:
  - type: turn_off
    device_id: 55ab137d1334f604e4eaf1080252f16d
    entity_id: switch.blitzwolf_bwshp15_01
    domain: switch
  mode: single
- id: '1668957815753'
  alias: Turn off bedside light Lize
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.sgs10_lize_is_aan_het_opladen
    to: 'off'
    from: 'on'
  condition: []
  action:
  - type: turn_off
    device_id: faad4b192378e316257a2e8d2980cdcd
    entity_id: light.ikea_nightlight_02
    domain: light
  mode: single
- id: '1668971498514'
  alias: Wake up light André
  description: ''
  trigger:
  - platform: time
    at: input_datetime.next_alarm
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: person.andre_de_zwart
      state: home
    - condition: state
      entity_id: binary_sensor.sm_g991b_is_charging
      state: 'on'
  action:
  - type: turn_on
    device_id: dfedf6a047a478d4540755ce837b2d82
    entity_id: light.ikea_nightlight_01
    domain: light
    brightness_pct: 1
  mode: single
- id: '1669754804462'
  alias: Android alarm time
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.phone_andre_next_alarm
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.phone_andre_next_alarm
      state:
      - unavailable
      - unknown
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: input_datetime.set_datetime
    data_template:
      datetime: '{{ as_timestamp(states(''sensor.phone_andre_next_alarm'')) | timestamp_custom(''%Y-%m-%d
        %H:%M:00'') }}'
    target:
      entity_id: input_datetime.next_alarm
  mode: single
- id: '1673262664635'
  alias: Turn off hallway light after 7 min
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.shelly1_hallway
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.xiaomi_door_01_contact
    to: 'on'
  condition:
  - condition: state
    entity_id: light.shelly1_hallway
    state: 'on'
  action:
  - delay:
      hours: 0
      minutes: 7
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.shelly1_hallway
  mode: restart
