- id: '1619338510649'
  alias: Sleep Mode when phones charging
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.sm_g973f_is_charging
    to: 'on'
  - platform: state
    entity_id: binary_sensor.sgs10_lize_is_aan_het_opladen
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.sm_g973f_is_charging
      state: 'on'
    - condition: state
      entity_id: binary_sensor.sgs10_lize_is_aan_het_opladen
      state: 'on'
    - condition: time
      after: '19:00:00'
  action:
  - service: homeassistant.turn_off
    target:
      area_id:
      - c9c7d949cb959b8436f04d3b8e02018a
      - 5725600297af4a14beb939fde831b3e9
      - e0451735c3764eebbf1c3fece20c87e9
      - 940887afcb1047b2b74fad4a446ce8b9
      - 10320c5721484f4c87ad56a96e8f441c
      - 75e0dbc9fbbe436db390faa9e7ff08c7
  mode: single
- id: '1619375794749'
  alias: Left at KDV notification
  description: ''
  trigger:
  - platform: zone
    entity_id: person.lize_wasmus
    zone: zone.kdv_het_tuinhuis
    event: leave
  condition:
  - condition: time
    after: '16:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
  - service: notify.mobile_app_sgs10_andre
    data_template:
      message: '{{trigger.entity_id.friendly_name}} is vertrokken bij Het Tuinhuis'
  mode: single
