- id: '1578239116640'
  alias: Turn on the front door light before coming home
  description: ''
  trigger:
  - below: '-2.0'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state_attr(''sun.sun'', ''elevation'') }}'
  condition:
  - after: '15:00:00'
    before: '22:45:00'
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - device_id: 81034ef9b8e7499d886c9c5c17fe7d5a
    domain: switch
    entity_id: switch.outside
    type: turn_on
- id: '1581245071438'
  alias: Turn on the front door light before leaving home
  description: ''
  trigger:
  - below: '2'
    entity_id: sun.sun
    platform: numeric_state
    value_template: '{{ state_attr(''sun.sun'', ''elevation'') }}'
  condition:
  - after: 06:00:00
    before: 07:15:00
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - device_id: 81034ef9b8e7499d886c9c5c17fe7d5a
    domain: switch
    entity_id: switch.outside
    type: turn_on
- id: '1581273016748'
  alias: Turn off front door light during the night or during the day
  description: ''
  trigger:
  - at: '23:00:00'
    platform: time
  - at: 07:30:00
    platform: time
  condition: []
  action:
  - device_id: 81034ef9b8e7499d886c9c5c17fe7d5a
    domain: switch
    entity_id: switch.outside
    type: turn_off
- alias: 'Trash collection notification'
  trigger:
  - platform: time_pattern
    hours: /1
    minutes: 0
    seconds: 0
  condition:
  - condition: and
    conditions:
    - condition: template
      value_template: >
        {% if (as_timestamp(now()) > (as_timestamp(states.sensor.afvalkalender_event_0.attributes.start) - 16200)) %}
          true
        {% endif %}
    - condition: template
      value_template: >
        {% if (as_timestamp(states.sensor.afvalkalender_event_0.attributes.start)) - (as_timestamp(now()) > 0) %}
          true
        {% endif %}
  action:
  - service: notify.telegram_andre
    data_template:
      message: '{{states.sensor.afvalkalender_event_0.attributes.name}} wordt morgen opgehaald.'
  - service: notify.telegram_lize
    data_template:
      message: '{{states.sensor.afvalkalender_event_0.attributes.name}} wordt morgen opgehaald.'
