
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
 http:
   base_url: !secret base_url

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

binary_sensor:
  - platform: stookalert
    province: !secret province

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret chat_id_andre
      - !secret chat_id_lize
      - !secret chat_id_reigeroord

notify:
  - name: telegram_andre
    platform: telegram
    chat_id: !secret chat_id_andre
  - name: telegram_lize
    platform: telegram
    chat_id: !secret chat_id_lize
  - name: telegram_reigeroord
    platform: telegram
    chat_id: !secret chat_id_reigeroord

camera:
  - platform: generic
    name: Frontdoor camera 1
    still_image_url: !secret frontdoor_ip_cam_still_image_url
    stream_source: !secret frontdoor_ip_cam_stream_source

media_player:
  - platform: lg_netcast
    host: !secret lg_ip_address
    access_token: !secret lg_access_token

sensor:
  - platform: ical
    name: "Afvalkalender"
    url: "https://afvalkalender.cyclusnv.nl/ical/0497200000006797"
    maxevents: 3

  - platform: dsmr
    dsmr_version: 5

  - platform: cert_expiry
    host: !secret base_url

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: swap_use_percent
      - type: processor_use

  - platform: growatt_server
    username: !secret growatt_username
    password: !secret growatt_password

  - platform: nederlandse_spoorwegen
    api_key: !secret ns_api_key
    routes:
      - name: Bodegraven - Leiden
        from: Bdg
        to: Ledn
        time: !secret ns_bl_departure
      - name: Leiden - Bodegraven
        from: Ledn
        to: Bdg
        time: !secret ns_lb_departure
      - name: Bodegraven - Utrecht
        from: Bdg
        to: Ut
        time: !secret ns_bu_departure
      - name: Utrecht - Bodegraven
        from: Ut
        to: Bdg
        time: !secret ns_ub_departure

  - platform: buienradar
    name: 'Buienradar'
    monitored_conditions:
      # Current contition:
      - stationname
      - conditiondetailed
      - symbol
      - feeltemperature
      - humidity
      - temperature
      - precipitation
      - precipitation_forecast_average
      - precipitation_forecast_total
      # Forecasted contitions:
      - symbol_1d
      - temperature_1d
      - rainchance_1d
      - rain_1d
      - minrain_1d
      - maxrain_1d
      - symbol_2d
      - temperature_2d
      - rainchance_2d
      - symbol_3d
      - temperature_3d
      - rainchance_3d

  - platform: template
    sensors:
      trash_0:
        friendly_name_template: '{{ state_attr(''sensor.afvalkalender_event_0'', ''name'')}}'
        value_template: "{{ as_timestamp(states.sensor.afvalkalender_event_0.attributes.start) | timestamp_custom('%d %b %Y') }}"
        icon_template: >-
            {% if 'Plastic' in state_attr('sensor.afvalkalender_event_0', 'name') %}
              mdi:sack
            {% elif 'Papier' in state_attr('sensor.afvalkalender_event_0', 'name') %}
              mdi:package-variant
            {% else %}
              mdi:trash-can-outline
            {% endif %}
      trash_1:
        friendly_name_template: '{{ state_attr(''sensor.afvalkalender_event_1'', ''name'')}}'
        value_template: "{{ as_timestamp(states.sensor.afvalkalender_event_1.attributes.start) | timestamp_custom('%d %b %Y') }}"
        icon_template: >-
            {% if 'Plastic' in state_attr('sensor.afvalkalender_event_1', 'name') %}
              mdi:sack
            {% elif 'papier' in state_attr('sensor.afvalkalender_event_1', 'name') %}
              mdi:package-variant
            {% else %}
              mdi:trash-can-outline
            {% endif %}
      trash_2:
        friendly_name_template: '{{ state_attr(''sensor.afvalkalender_event_2'', ''name'')}}'
        value_template: "{{ as_timestamp(states.sensor.afvalkalender_event_2.attributes.start) | timestamp_custom('%d %b %Y') }}"
        icon_template: >-
            {% if 'Plastic' in state_attr('sensor.afvalkalender_event_2', 'name') %}
              mdi:sack
            {% elif 'papier' in state_attr('sensor.afvalkalender_event_2', 'name') %}
              mdi:package-variant
            {% else %}
              mdi:trash-can-outline
            {% endif %}
