# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

homeassistant:
  packages: !include_dir_named ./integrations
  allowlist_external_dirs:
    - /tmp
  customize: !include customize.yaml

automation: !include automations.yaml
automation split: !include_dir_merge_list automations

alert: !include alerts.yaml
group: !include groups.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors

light:
  - platform: group
    name: TV cabinet
    entities:
      - light.tv_cabinet_left
      - light.tv_cabinet_right      
