# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

homeassistant:
  packages: !include_dir_named ./integrations
  allowlist_external_dirs:
    - /tmp
  customize: !include customize.yaml

automation: !include automations.yaml
automation split: !include_dir_merge_list automations

group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors

binary_sensor:
  - platform: stookalert
    province: !secret province

  - platform: workday
    country: NL
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun]

  - platform: ping
    name: "Netgear ReadyNAS NV+ v2"
    host: 192.168.2.15

ffmpeg:

# influxdb:
#   host: 192.168.2.100
#   include:
#     domains:
#       - sensor 