# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

homeassistant:
  packages: !include_dir_named ./integrations
  allowlist_external_dirs:
    - /tmp

automation: !include automations.yaml
automation split: !include_dir_merge_list automations

group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors

binary_sensor:
  - platform: stookalert
    province: !secret province

  - platform: workday
    country: NL
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun]

  - platform: ping
    name: "Netgear ReadyNAS NV+ v2"
    host: 192.168.2.15

  - platform: template
    sensors:
      is_on_call:
        friendly_name: "On call"
        value_template: "{{ is_state('sensor.opsgenie_on_call', states('sensor.opsgenie_participant_id')) }}"
        icon_template: >-
          {% if is_state('sensor.opsgenie_on_call', states('sensor.opsgenie_participant_id')) %}
            mdi:phone-alert
          {% else %}
            mdi:phone-off
          {% endif %}

ffmpeg:

# influxdb:
#   host: 192.168.2.100
#   include:
#     domains:
#       - sensor 