# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

homeassistant:
  packages: !include_dir_named ./integrations
  allowlist_external_dirs:
    - /tmp
  customize: !include customize.yaml

# logger:
#   default: warning
#   logs:
#     custom_components.nefiteasy: debug
#     aionefit: debug

sonos:
  media_player:
    advertise_addr: 192.168.2.100

automation: !include automations.yaml
automation split: !include_dir_merge_list automations

alert: !include alerts.yaml
group: !include groups.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors

command_line:
  - sensor:
      command: "cat /sys/class/thermal/thermal_zone0/temp"
      name: CPU Temperature
      unit_of_measurement: "°C"
      value_template: "{{ (value | multiply(0.001)) | round(1) }}"

light:
  - platform: group
    name: TV cabinet
    entities:
      - light.tv_cabinet_left
      - light.tv_cabinet_right
