
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

homeassistant:
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /tmp

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors

binary_sensor:
  - platform: stookalert
    province: !secret province

  - platform: workday
    country: NL
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun]

  - platform: ping
    name: "Netgear ReadyNAS NV+ v2"
    host: 192.168.2.15

switch:
  - platform: wake_on_lan
    name: "Netgear ReadyNAS NV+ v2"
    mac: e0:46:9a:a0:57:03
    broadcast_address: 192.168.2.15
    broadcast_port: 9

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret chat_id_andre
      - !secret chat_id_lize
      - !secret chat_id_reigeroord

notify:
  - name: telegram_andre
    platform: telegram
    chat_id: !secret chat_id_andre
  - name: telegram_lize
    platform: telegram
    chat_id: !secret chat_id_lize
  - name: telegram_reigeroord
    platform: telegram
    chat_id: !secret chat_id_reigeroord

ffmpeg:

camera:
  - platform: generic
    name: Frontdoor camera 1
    still_image_url: !secret frontdoor_ip_cam_still_image_url
    stream_source: !secret frontdoor_ip_cam_stream_source

media_player:
  - platform: lg_netcast
    host: !secret lg_ip_address
    access_token: !secret lg_access_token

influxdb:
  host: 192.168.2.100
  include:
    domains:
      - sensor

nefiteasy:
  devices:
  - serial: !secret nefit_easy_serial
    accesskey: !secret nefit_easy_accesskey
    password: !secret nefit_easy_password

pi_hole:
  host: 192.168.2.100
  name: pihole
  api_key: !secret pi_hole_api_token

vacuum:
  - platform: xiaomi_miio
    host: 192.168.2.176
    token: !secret roborock_token

monitor_docker:
  - name: Docker
    containers:
      - grafana
      - home-assistant
      - influxdb
      - mosquitto
      - pihole
      - portainer
      - swag
    rename:
      home-assistant: Home Assistant
      influxdb: InfluxDB
      grafana: Grafana
      portainer: Portainer
      swag: Secure Web Application Gateway
      pihole: Pi Hole
    monitored_conditions:
      - version
      - containers_total
      - containers_running
      - containers_paused
      - containers_stopped
      - containers_cpu_percentage
      - containers_memory
      - containers_memory_percentage
      - images
      - uptime
      - image
      - cpu_percentage
      - memory
      - memory_percentage