- platform: nederlandse_spoorwegen
  api_key: !secret ns_api_key
  routes:
    - name: Bodegraven - Leiden
      from: Bdg
      to: Ledn
      time: !secret ns_bl_departure
    - name: Leiden - Bodegraven
      from: Ledn
      to: Bdg
      time: !secret ns_lb_departure
    - name: Bodegraven - Utrecht
      from: Bdg
      to: Ut
      time: !secret ns_bu_departure
    - name: Utrecht - Bodegraven
      from: Ut
      to: Bdg
      time: !secret ns_ub_departure