- platform: snmp
  host: 192.168.2.15
  baseoid: 1.3.6.1.2.1.25.1.1.0
  name: 'Netgear ReadyNAS NV+ v2 Uptime'
  value_template: >-
    {% set time = (value | int) | int %}
    {% set minutes = ((time % 360000) / 6000) | int%}
    {% set hours = ((time % 8640000) / 360000) | int %}
    {% set days = (time / 8640000) | int %}
      {%- if time < 60 -%}
        Less then 1 min
        {%- else -%}
        {%- if days > 0 -%}
          {{ days }}d
        {%- endif -%}
        {%- if hours > 0 -%}
          {%- if days > 0 -%}
            {{ ' ' }}
          {%- endif -%}
          {{ hours }}hr
        {%- endif -%}
        {%- if minutes > 0 -%}
          {%- if days > 0 or hours > 0 -%}
            {{ ' ' }}
          {%- endif -%}
          {{ minutes }}min
        {%- endif -%}
      {%- endif -%}
  
- platform: snmp
  host: 192.168.2.15
  baseoid: 1.3.6.1.2.1.1.5.0
  name: 'Netgear ReadyNAS NV+ v2 Name'