- platform: template
  sensors:
    trash_0:
      friendly_name_template: "{{ state_attr('sensor.ical_afvalkalender_event_0', 'description')}}"
      value_template: "{{ as_timestamp(states.sensor.ical_afvalkalender_event_0.attributes.start) | timestamp_custom('%d %b %Y') }}"
      icon_template: >-
          {% if 'Plastic' in state_attr('sensor.ical_afvalkalender_event_0', 'description') %}
            mdi:sack
          {% elif 'papier' in state_attr('sensor.ical_afvalkalender_event_0', 'description') %}
            mdi:package-variant
          {% else %}
            mdi:trash-can-outline
          {% endif %}

    trash_1:
      friendly_name_template: "{{ state_attr('sensor.ical_afvalkalender_event_1', 'description')}}"
      value_template: "{{ as_timestamp(states.sensor.ical_afvalkalender_event_1.attributes.start) | timestamp_custom('%d %b %Y') }}"
      icon_template: >-
          {% if 'Plastic' in state_attr('sensor.ical_afvalkalender_event_1', 'description') %}
            mdi:sack
          {% elif 'papier' in state_attr('sensor.ical_afvalkalender_event_1', 'description') %}
            mdi:package-variant
          {% else %}
            mdi:trash-can-outline
          {% endif %}

    trash_2:
      friendly_name_template: "{{ state_attr('sensor.ical_afvalkalender_event_2', 'description')}}"
      value_template: "{{ as_timestamp(states.sensor.ical_afvalkalender_event_2.attributes.start) | timestamp_custom('%d %b %Y') }}"
      icon_template: >-
          {% if 'Plastic' in state_attr('sensor.ical_afvalkalender_event_2', 'description') %}
            mdi:sack
          {% elif 'papier' in state_attr('sensor.ical_afvalkalender_event_2', 'description') %}
            mdi:package-variant
          {% else %}
            mdi:trash-can-outline
          {% endif %}

    trash_pmd:
      friendly_name_template: "Plastic, metaal en drankenkartons"
      icon_template: mdi:sack
      value_template: >-
        {% if 'Plastic' in state_attr('sensor.ical_afvalkalender_event_0', 'description') %}
          {{ as_timestamp(states.sensor.ical_afvalkalender_event_0.attributes.start) | timestamp_custom('%d %b %Y') }}

        {% elif 'Plastic' in state_attr('sensor.ical_afvalkalender_event_1', 'description') %}
          {{ as_timestamp(states.sensor.ical_afvalkalender_event_1.attributes.start) | timestamp_custom('%d %b %Y') }}

        {% elif 'Plastic' in state_attr('sensor.ical_afvalkalender_event_2', 'description') %}
          {{ as_timestamp(states.sensor.ical_afvalkalender_event_2.attributes.start) | timestamp_custom('%d %b %Y') }}

        {% elif 'Plastic' in state_attr('sensor.ical_afvalkalender_event_3', 'description') %}
          {{ as_timestamp(states.sensor.ical_afvalkalender_event_2.attributes.start) | timestamp_custom('%d %b %Y') }}

        {% elif 'Plastic' in state_attr('sensor.ical_afvalkalender_event_4', 'description') %}
          {{ as_timestamp(states.sensor.ical_afvalkalender_event_4.attributes.start) | timestamp_custom('%d %b %Y') }}

        {% elif 'Plastic' in state_attr('sensor.ical_afvalkalender_event_5', 'description') %}
          {{ as_timestamp(states.sensor.ical_afvalkalender_event_5.attributes.start) | timestamp_custom('%d %b %Y') }}

        {% endif %}      
          
    trash_gtf:
      friendly_name_template: "Groente-, fruit- en tuinafval"
      icon_template: mdi:trash-can-outline
      value_template: >-
        {% if 'Groente' in state_attr('sensor.ical_afvalkalender_event_0', 'description') %}
          {{ as_timestamp(states.sensor.ical_afvalkalender_event_0.attributes.start) | timestamp_custom('%d %b %Y') }}

        {% elif 'Groente' in state_attr('sensor.ical_afvalkalender_event_1', 'description') %}
          {{ as_timestamp(states.sensor.ical_afvalkalender_event_1.attributes.start) | timestamp_custom('%d %b %Y') }}

        {% elif 'Groente' in state_attr('sensor.ical_afvalkalender_event_2', 'description') %}
          {{ as_timestamp(states.sensor.ical_afvalkalender_event_2.attributes.start) | timestamp_custom('%d %b %Y') }}

        {% elif 'Groente' in state_attr('sensor.ical_afvalkalender_event_3', 'description') %}
          {{ as_timestamp(states.sensor.ical_afvalkalender_event_2.attributes.start) | timestamp_custom('%d %b %Y') }}

        {% elif 'Groente' in state_attr('sensor.ical_afvalkalender_event_4', 'description') %}
          {{ as_timestamp(states.sensor.ical_afvalkalender_event_4.attributes.start) | timestamp_custom('%d %b %Y') }}

        {% elif 'Groente' in state_attr('sensor.ical_afvalkalender_event_5', 'description') %}
          {{ as_timestamp(states.sensor.ical_afvalkalender_event_5.attributes.start) | timestamp_custom('%d %b %Y') }}

        {% endif %}
          
    trash_paper:
      friendly_name_template: "Oud papier & karton"
      icon_template: mdi:package-variant
      value_template: >-
        {% if 'papier' in state_attr('sensor.ical_afvalkalender_event_0', 'description') %}
          {{ as_timestamp(states.sensor.ical_afvalkalender_event_0.attributes.start) | timestamp_custom('%d %b %Y') }}

        {% elif 'papier' in state_attr('sensor.ical_afvalkalender_event_1', 'description') %}
          {{ as_timestamp(states.sensor.ical_afvalkalender_event_1.attributes.start) | timestamp_custom('%d %b %Y') }}

        {% elif 'papier' in state_attr('sensor.ical_afvalkalender_event_2', 'description') %}
          {{ as_timestamp(states.sensor.ical_afvalkalender_event_2.attributes.start) | timestamp_custom('%d %b %Y') }}

        {% elif 'papier' in state_attr('sensor.ical_afvalkalender_event_3', 'description') %}
          {{ as_timestamp(states.sensor.ical_afvalkalender_event_3.attributes.start) | timestamp_custom('%d %b %Y') }}

        {% elif 'papier' in state_attr('sensor.ical_afvalkalender_event_4', 'description') %}
          {{ as_timestamp(states.sensor.ical_afvalkalender_event_4.attributes.start) | timestamp_custom('%d %b %Y') }}

        {% elif 'papier' in state_attr('sensor.ical_afvalkalender_event_5', 'description') %}
          {{ as_timestamp(states.sensor.ical_afvalkalender_event_5.attributes.start) | timestamp_custom('%d %b %Y') }}

        {% endif %}

    power_direct_usage:
      friendly_name: "Direct Power Usage"
      unique_id: "sensor.direct_power_usage"
      unit_of_measurement: "W"
      value_template: "{{ ((states('sensor.growatt_total_output_power') | float) - ((states('sensor.power_production') | float) * 1000)) | round(2) }}"

    nefit_temperature:
      friendly_name: "Nefit Set temperature"
      unique_id: "sensor.nefit_temperature"
      unit_of_measurement: "°C"
      value_template: "{{ state_attr('climate.nefit', 'temperature') }}"

    nefit_current_temperature:
      friendly_name: "Nefit Current temperature"
      unique_id: "sensor.nefit_current_temperature"
      unit_of_measurement: "°C"
      value_template: "{{ state_attr('climate.nefit', 'current_temperature') }}"

    office_temperature:
      friendly_name: "Office Current temperature"
      unique_id: "sensor.office_current_temperature"
      unit_of_measurement: "°C"
      value_template: "{{ state_attr('climate.office', 'current_temperature') }}"

    opsgenie_participant_id:
      value_template: !secret genie_participant_name