- platform: template
  sensors:
    trash_0:
      friendly_name_template: "{{ state_attr('sensor.ical_afvalkalender_event_0', 'description')}}"
      value_template: >-
        {% if states.sensor.ical_afvalkalender_event_0 is defined and states.sensor.ical_afvalkalender_event_0 != None and 'start' in states.sensor.ical_afvalkalender_event_0.attributes %}
          {{ as_timestamp(states.sensor.ical_afvalkalender_event_0.attributes.start) | timestamp_custom('%d %b %Y') }}
        {% else %}
          ""
        {% endif %}
      icon_template: >-
        {% if states.sensor.ical_afvalkalender_event_0 is defined and states.sensor.ical_afvalkalender_event_0 != None and 'start' in states.sensor.ical_afvalkalender_event_0.attributes %}
          {% if 'Plastic' in state_attr('sensor.ical_afvalkalender_event_0', 'description') %}
            mdi:sack
          {% elif 'papier' in state_attr('sensor.ical_afvalkalender_event_0', 'description') %}
            mdi:package-variant
          {% else %}
            mdi:trash-can-outline
          {% endif %}
        {% endif %}

    trash_1:
      friendly_name_template: "{{ state_attr('sensor.ical_afvalkalender_event_1', 'description')}}"
      value_template: >-        
        {% if states.sensor.ical_afvalkalender_event_1 is defined and states.sensor.ical_afvalkalender_event_1 != None and 'start' in states.sensor.ical_afvalkalender_event_1.attributes %}
          {{ as_timestamp(states.sensor.ical_afvalkalender_event_1.attributes.start) | timestamp_custom('%d %b %Y') }}
        {% else %}
          ""
        {% endif %}     
      icon_template: >-        
        {% if states.sensor.ical_afvalkalender_event_1 is defined and states.sensor.ical_afvalkalender_event_1 != None and 'start' in states.sensor.ical_afvalkalender_event_1.attributes %}
          {% if 'Plastic' in state_attr('sensor.ical_afvalkalender_event_1', 'description') %}
            mdi:sack
          {% elif 'papier' in state_attr('sensor.ical_afvalkalender_event_1', 'description') %}
            mdi:package-variant
          {% else %}
            mdi:trash-can-outline
          {% endif %}
        {% endif %}

    trash_2:
      friendly_name_template: "{{ state_attr('sensor.ical_afvalkalender_event_2', 'description')}}"
      value_template: >-
        {% if states.sensor.ical_afvalkalender_event_2 is defined and states.sensor.ical_afvalkalender_event_2 != None and 'start' in states.sensor.ical_afvalkalender_event_2.attributes %}
          {{ as_timestamp(states.sensor.ical_afvalkalender_event_2.attributes.start) | timestamp_custom('%d %b %Y') }}
        {% else %}
          ""
        {% endif %}
      icon_template: >-
        {% if states.sensor.ical_afvalkalender_event_2 is defined and states.sensor.ical_afvalkalender_event_2 != None and 'start' in states.sensor.ical_afvalkalender_event_2.attributes %}
          {% if 'Plastic' in state_attr('sensor.ical_afvalkalender_event_2', 'description') %}
            mdi:sack
          {% elif 'papier' in state_attr('sensor.ical_afvalkalender_event_2', 'description') %}
            mdi:package-variant
          {% else %}
            mdi:trash-can-outline
          {% endif %}
        {% endif %}

    power_direct_usage:
      friendly_name: "Direct Power Usage"
      unique_id: "sensor.direct_power_usage"
      unit_of_measurement: "W"
      value_template: "{{ ((states('sensor.growatt_total_output_power') | float) - ((states('sensor.power_production') | float) * 1000)) | round(2) }}"

    nefit_temperature:
      friendly_name: "Nefit Set temperature"
      unique_id: "sensor.nefit_temperature"
      unit_of_measurement: "°C"
      value_template: "{{ state_attr('climate.nefit', 'temperature') }}"

    nefit_current_temperature:
      friendly_name: "Nefit Current temperature"
      unique_id: "sensor.nefit_current_temperature"
      unit_of_measurement: "°C"
      value_template: "{{ state_attr('climate.nefit', 'current_temperature') }}"

    office_temperature:
      friendly_name: "Office Current temperature"
      unique_id: "sensor.office_current_temperature"
      unit_of_measurement: "°C"
      value_template: "{{ state_attr('climate.office', 'current_temperature') }}"

    buienradar_rain_expected:
      friendly_name: "Buienradar neerslag verwacht"
      unique_id: "binary_sensor.neerslag_buienradar_rain_expected"
      value_template: >-
        {% if states.sensor.neerslag_buienradar_regen_data.attributes.data is defined and states.sensor.neerslag_buienradar_regen_data.attributes.data != None %}  
          {% set buienradar_data = state_attr('sensor.neerslag_buienradar_regen_data', 'data').split(" ") %}
          {% if buienradar_data|length > 1 %}
            {% if (buienradar_data[0].split("|")|first|int + buienradar_data[1].split("|")|first|int + buienradar_data[2].split("|")|first|int) > 0 -%}
              true  
            {% else %}
              false  
            {% endif %}
          {% endif %}
        {% else %}
            false  
        {% endif %}

    buienalarm_rain_expected:
      friendly_name: "Buienalarm neerslag verwacht"
      unique_id: "binary_sensor.neerslag_buienalarm_rain_expected"
      value_template: >-
        {% if states.sensor.neerslag_buienalarm_regen_data.attributes.data['precip'] is defined and states.sensor.neerslag_buienalarm_regen_data.attributes.data['precip'] != None %}
          {% if (states.sensor.neerslag_buienalarm_regen_data.attributes.data.precip[0] + states.sensor.neerslag_buienalarm_regen_data.attributes.data.precip[1] + states.sensor.neerslag_buienalarm_regen_data.attributes.data.precip[2]) > 0 -%}
              true
          {% else %}
              false
          {% endif %}
        {% else %}
              false
        {% endif %}
